{% set version = "1.4.1" %}

package:
  name: protoc-gen-go
  version: {{ version }}

source:
  url : https://github.com/golang/protobuf/archive/v{{ version }}.tar.gz
  sha256: f0185157c9042484f7014836b5b0e8e37409aecef83108779ec15bc510e93c8a

build:
  number: 0
  script:
    - go install -v ./protoc-gen-go

requirements:
  build:
    - {{ compiler('go') }} 1.13

test:
  commands:
    # no --version command exists
    - which protoc-gen-go  # [unix]
    - where protoc-gen-go  # [win]

about:
  home: https://github.com/golang/protobuf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Go support for Protocol Buffers - Google's data interchange format

extra:
  recipe-maintainers:
    - hmaarrfk
